services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eazybank
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432