spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/eazybank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/migration/changelog.yml
    default-schema: public

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: debug

