spring:

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5689829c835a8cf30709
            client-secret: d8f25d90398c85d4cd85ce90eca642a19a974b87

