spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/eazybank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migration/changelog.yml
    default-schema: public

